gaps.exceptions.gapsRuntimeError
================================

.. currentmodule:: gaps.exceptions

.. autoexception:: gapsRuntimeError